#Orginal Code generated by perplexity
#https://www.perplexity.ai/search/xrp-robot-nLBJdc69TyCWxMoTcXne2A
#Code will only work with Modifications

import xrplib #wrong library "from XRPLib.defaults import *"
import time

# Initialize the drivetrain
drivetrain = xrplib.Drivetrain()

# Move forward at half effort (both wheels forward)
drivetrain.set_effort(0.5, 0.5)
time.sleep(2)  # Move forward for 2 seconds

# Stop
drivetrain.set_effort(0, 0)
time.sleep(1)  # Pause for 1 second

# Move backward at half effort (both wheels backward)
drivetrain.set_effort(-0.5, -0.5)
time.sleep(2)  # Move backward for 2 seconds

# Stop
drivetrain.set_effort(0, 0)
