#Working Code: Modified org generated by perplexity
#https://www.perplexity.ai/search/xrp-robot-nLBJdc69TyCWxMoTcXne2A

'''Change 1'''
#import xrplib                #Change 1 :wrong library 
from XRPLib.defaults import * #Change 1  :Changed lib import


import time

'''Change 2'''
# Initialize the drivetrain
#drivetrain = xrplib.Drivetrain() #Change 2: Removed


# Move forward at half effort (both wheels forward)
drivetrain.set_effort(0.5, 0.5)
time.sleep(2)  # Move forward for 2 seconds

# Stop
drivetrain.set_effort(0, 0)
time.sleep(1)  # Pause for 1 second

# Move backward at half effort (both wheels backward)
drivetrain.set_effort(-0.5, -0.5)
time.sleep(2)  # Move backward for 2 seconds

# Stop
drivetrain.set_effort(0, 0)
